### ISSUE TITLE
Question: Domain name

### ISSUE THREAD

**Issue by ArtMin96** [systemsdk/docker-nginx-php-laravel#51]
How can I add a domain name? Which will not conflict with local machine 127.0.0.1. Thanks

**Comment by ArtMin96** [comment]
Thanks :+1:

**Comment by ArtMin96** [comment]
@dimadeush If I write the domain name in `nginx.conf`, other users have to change the domain name in their `nginx.conf` every time. What is the best way to solve this problem? Thanks

**Comment by dimadeush** [comment]
Hello Arthur
I don't know why do you need to change nginx.conf and why do you think that other users have to change it too. Maybe you are solving some your unique issue but I don't know anything about that. If I need to use some domain name and not localhost or 127.0.0.1 - I'm doing it via hosts file for my OS (https://www.hostinger.com/tutorials/wp-content/uploads/sites/2/2016/06/add-ip-address-on-hosts-file.webp).
