### ISSUE TITLE
unable to connect to dbbeaver

### ISSUE THREAD

**Issue by constantinosergiou** [systemsdk/docker-nginx-php-laravel#52]
i can connect through terminal by using 
 
 mysql -h mysql -u root -psecret laravel

but when i try to connect to dbbeaver i get connection refused.

what is the issue?

**Comment by dimadeush** [comment]
It can be the issue with your dbbeaver or wrong connection params.  Maybe you need to try host 127.0.0.1, port 33061

**Comment by constantinosergiou** [comment]
works thanks
