### ISSUE TITLE
php-dev has no installation candidate

### ISSUE THREAD

**Issue by Vergazov** [systemsdk/docker-nginx-php-laravel#54]
I'm trying to install php-dev package.
But when I try, I get an error "php-dev has no installation candidate".
Maybe you can tell me what can be done to solve this problem

**Comment by dimadeush** [comment]
Plz try notes here - https://stackoverflow.com/questions/47691057/debian-9-the-php5-packages-is-not-installed

**Comment by Vergazov** [comment]
thank you
